version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "33060:3306"

    command: --default-authentication-plugin=mysql_native_password

    volumes:
      mysql-data:
